# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_free', models.NullBooleanField(verbose_name='Бесплатное событие')),
                ('age_restricted', models.CharField(blank=True, max_length=3, null=True, verbose_name='Возрастная категория')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('text', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('start', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('finish', models.TimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Event')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='events',
            field=models.ManyToManyField(through='content.Schedule', to='content.Event'),
        ),
    ]
